### ISSUE TITLE
Configure the hidden service automatically

### ISSUE THREAD

**Issue by photm5** [Jugendhackt/haskell-ricochet#12]
This will require a pull request to `network-anonymous-tor`. For now, I propose to let the users configure it themselves.

**Comment by sternenseemann** [comment]
Example torrc commited as of ba810d1fd8f0d433f7418f189697a00f1bf98015

**Comment by sternenseemann** [comment]
@froozen's [Pull Request](https://github.com/solatis/haskell-network-anonymous-tor/pull/4) is pending.

**Comment by photm5** [comment]
The PR is merged by now.  @froozen does it suffice for our needs?

Do we plan to add a small wrapper to this library?

**Comment by froozen** [comment]
I'd propose having the user of the just pass in a `Socket` when they want to run the `Ricochet`-Monad, as they can simply open it themselves, if they already configured the hidden service in their tor instance or use [network-anonymous-tor](https://hackage.haskell.org/package/network-anonymous-tor) to do it for them.
This would clash with #18, though, as `network-anonymous-tor` uses `Network.Socket` in their interface, which we would have to use as well then.

**Comment by photm5** [comment]
The implementation of accepting a `Socket` connection in `network-anonymous-tor` is merely a small wrapper, if I remember right.  This means we could rewrite that wrapper to use `haskell-socket` and add it to this library.  Problematic might be that probably there are lots of more libraries out there that support the `Network.Socket` interface.

What do you think?

**Comment by froozen** [comment]
I guess we should have @lukasepple explain to us why he thinks we should use `haskell-socket` instead and decide then wether it's worth the trouble.

**Comment by sternenseemann** [comment]
Platform independant and POSIX compliant interface.

**Comment by froozen** [comment]
Platform independant as in Windows compatible?

**Comment by sternenseemann** [comment]
[Yes](https://github.com/lpeterse/haskell-socket#platform-support)

**Comment by froozen** [comment]
I don't think better POSIX compliance is an equal tradeoff for compatability to other libraries.
We should use `Network.Socket`, at least until we start having problems with it.

**Comment by sternenseemann** [comment]
Why would we drop compatibility with other libraries?

**Comment by photm5** [comment]
Because other libraries might provide means of creating `Network.Socket` instances.  Our library would only be capable of handling `System.Socket.Socket` instances.

**Comment by froozen** [comment]
Because there's a lot of libraries providing utility functionality for `Network.Socket` that users of our library might want to use, like [network-attoparsec](https://hackage.haskell.org/package/network-attoparsec-0.12.2/docs/Network-Attoparsec.html#parseMany). This would be impossible if we used `System.Socket.Socket`.

**Comment by photm5** [comment]
:)

**Comment by sternenseemann** [comment]
I see.

**Comment by sternenseemann** [comment]
What is the status here?

**Comment by froozen** [comment]
Should've been closed by merging #33.
