### ISSUE TITLE
Unify naming scheme

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/haskell-ricochet#13]
- Is it a Ricochet User, Instance or Node?
- …

**Comment by sternenseemann** [comment]
We probably should follow these [Conventions](https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md#conventions)

**Comment by photm5** [comment]
The Conventions don’t cover the question you raised in the description.  I’d vote for “Node”, as it fits in with “Peer”, since both seem to be used when discussing P2P applications.

**Comment by sternenseemann** [comment]
I think it is supposed to be a "Peer"

**Comment by photm5** [comment]
It depends on the context.  If we’re talking about the two sides of a connection, those are “Peers.”  But if we’re talking about any two clients in the network that might not be connected to each other those are “Nodes.” However, we won’t be talking about the latter until we’re extending the protocol, so you’re right in some way.

**Comment by sternenseemann** [comment]
I think @froozen already used the term "Peer" in his documentation PR

**Comment by photm5** [comment]
Is anything in “…” not covered by the Conventions?

**Comment by sternenseemann** [comment]
Huh?

**Comment by photm5** [comment]
I’m talking about the second item in the description. Worded differently: Is there anything else left to discuss here?

**Comment by sternenseemann** [comment]
I don't know…
