### ISSUE TITLE
Handle (unlikely) case of 0 supported versions

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/haskell-ricochet#14]
Problems could exist:
- …in `introductionParser`
- …in `initConnection`

**Comment by photm5** [comment]
It seems `initConnection` should behave correctly if `parseIntroduction` (Uses `introductionParser`) returns an empty Map.

**Comment by photm5** [comment]
``` haskell
ghci> instance Show (Connection -> Ricochet ()) where show = const "function"
ghci> parseIntroduction M.empty $ dumpIntroduction M.empty
Just (Just (fromList [],""))
```

Works.

**Comment by sternenseemann** [comment]
Nice, couldn't think clearly at 2am.
