### ISSUE TITLE
Initialize repository with cabal, nix, readme, license, etc

### ISSUE THREAD

**Issue by photm5** [Jugendhackt/haskell-ricochet#2]
What license do we want to use?  GPLv3 would be a nice choice, as crypto stuff should be as free as possible.
- [x] cabal
- [x] nix
- [x] readme
- [x] license

**Comment by sternenseemann** [comment]
No, let's use LGPL-3 to offer users of the library more (personal) freedom.

**Comment by sternenseemann** [comment]
:+1: for LGPL-3

**Comment by photm5** [comment]
:+1: for GPL-3

**Comment by froozen** [comment]
:+1: for GPLv3

**Comment by sternenseemann** [comment]
:+1: for GPL-3

**Comment by sternenseemann** [comment]
pff

**Comment by sternenseemann** [comment]
pff

**Comment by sternenseemann** [comment]
pff: 2
GPL-3: 3
LGPL-3: 1

**Comment by froozen** [comment]
https://youtu.be/zfAFUd1ZwB8

**Comment by fkarg** [comment]
Done
