### ISSUE TITLE
Packet transport not compatible with c++ implementation

### ISSUE THREAD

**Issue by photm5** [Jugendhackt/haskell-ricochet#21]
Somehow, we expect the package to be longer than it is, as we wait for more data even though all of it has arrived.  Reading through [the c++ implementation’s source code](https://github.com/ricochet-im/ricochet/blob/master/src/protocol/Connection.cpp#L442), I noticed they put the size of the whole message, including the header, in there.  This is not mentioned clearly enough [in the specification](https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md#packet-layer), so we should open an issue for it at the main project as soon as we can confirm this is correct.

**Comment by sternenseemann** [comment]
Thank you for investigating this.

**Comment by sternenseemann** [comment]
Well `Big endian, including the header bytes` is pretty clear…

**Comment by photm5** [comment]
I must’ve skipped that... So we won’t need to open an issue :). Could you fix and test this, as I didn’t manage to run the c++ implementation on NixOS yet?

**Comment by sternenseemann** [comment]
Yes

**Comment by sternenseemann** [comment]
I have rewritten the packet parser using attoparsec following the specification.

However the real reason why we haven't received any packets yet is because the server does not send any.

I think this is because we have to initiate a `im.ricochet.auth.hidden-service` channel first and prove that we are in control of our hidden service.

**Comment by photm5** [comment]
The c++ side did send packets when we were the server side :).

**Comment by sternenseemann** [comment]
oh, I tested the client side. Will test as server in a second

**Comment by sternenseemann** [comment]
Success!

I could receive first packets as a server:

```
We can choose between 1 versions!
We have chosen 1.
""
"\NUL=\NUL\NUL\n7\b\SOH\DC2\USim.ricochet.auth.hidden-service\130\194\ETX\DLE\226Kx\238\190\234\215\&4\252\&9\233\231Vo\\\205"
MkPacket {_pSize = 61, _pChannelID = 0, _pPacketData = "\n7\b\SOH\DC2\USim.ricochet.auth.hidden-service\130\194\ETX\DLE\226Kx\238\190\234\215\&4\252\&9\233\231Vo\\\205"}
```

**Comment by sternenseemann** [comment]
Corrected above comment. The odd responses were because I still was sending packets (code written for the demo).

**Comment by sternenseemann** [comment]
Before I push my changes I need to:
- … verify if it is correct what I am parsing
- … adjust the `dumpPacket` code

I am going to do that tomorrow.
