### ISSUE TITLE
Module `System.Process' does not export `callProcess'

### ISSUE THREAD

**Issue by fkarg** [Jugendhackt/haskell-ricochet#24]
Well, that was the error message when trying to build / configure cabal.
Assuming runProcess to be meant, it's complaining about Monoid not being in scope. Missing dependency?

**Comment by sternenseemann** [comment]
Can you paste the error message here? That would be very helpful. Probably it's related to your old cabal version.

**Comment by photm5** [comment]
What version of the `process` package do you have? (I think we need at least `1.2.0.0`.) You can find that out by running `ghc-pkg latest process`.

**Comment by fkarg** [comment]
well, apparently it's 1.1.0.2.
this still doesn't explain Monoid being out of scope? Either way we should fix it to run on other systems too.

**Comment by photm5** [comment]
Still, could you please paste the error message related to Monoid? I guess the `process` problem will be easy to fix, but I don’t quite understand what’s the issue with Monoid.

**Comment by fkarg** [comment]
Ah, now I got you:
When changing 'callProcess' to 'runProcess', I get the following error:

[1 of 1] Compiling Main             ( Setup.hs, dist/setup/Main.o )

Setup.hs:15:84: Not in scope: `mempty'

Setup.hs:21:23:
    Not in scope: type constructor or class `Monoid'
    Perhaps you meant`Monad' (imported from Prelude)

Setup.hs:24:22:
    Not in scope: type constructor or class `Monoid'
    Perhaps you meant`Monad' (imported from Prelude)

**Comment by fkarg** [comment]
mempty is another questionable one. the only module imported completely is 'Distribution.Simple', but it certainly isn't in the version I have at least

**Comment by sternenseemann** [comment]
Can you please check wether it is fixed on `build-system-fix`?

**Comment by fkarg** [comment]
still whining about 'callProcess'. but leaving this aside, he's complaining about something else now:

```
Setup.hs:15:63:
    Couldn't match expected type `IO a0'
                with actual type `Maybe FilePath
                                  -> Maybe [(String, String)]
                                  -> Maybe GHC.IO.Handle.Types.Handle
                                  -> Maybe GHC.IO.Handle.Types.Handle
                                  -> Maybe GHC.IO.Handle.Types.Handle
                                  -> IO System.Process.Internals.ProcessHandle'
    In the first argument of `(>>)', namely `runHprotoc'
    In the first argument of `const', namely
      `(runHprotoc >> return mempty)'
    In the first argument of `const', namely
      `(const (runHprotoc >> return mempty))'
Failed, modules loaded: none.
```

the operator itself is included in the Prelude even, meaning the issue is within `runHprotec`, which is, due to the unavailability of `callProcess` probably altered. My guess: it should work with updating the process module (callProcess), gotta figure out how to do it.

**Comment by fkarg** [comment]
Okay, after I found out how to update packages and such, process still got me some issues. when loading in ghci and trying to run it, he complained about two process instances ... working on that one.

another issue: when `cabal configure`-ing it, cabal insists `setup: hprotoc: does not exist`, even though I've confirmed its installation. 

Another issue I'm fighting with is the lack of easy uninstallation of packages and that I need to go somewhere in a few minutes, meaning I'll have to end it for today.

**Comment by sternenseemann** [comment]
Welcome to the cabal hell, dude.

**Comment by photm5** [comment]
> another issue: when cabal configure-ing it, cabal insists setup: hprotoc: does not exist, even though I've confirmed its installation. 

Did you put `~/.cabal/bin` into your `$PATH`?

**Comment by sternenseemann** [comment]
How does it look right now?

**Comment by fkarg** [comment]
Thing is, it worked. Or rather, it got me another error.

current status:
cabal is unable to build the package due to the bytestring package getting 'shadowed' or sth.
cabal is unable to sandbox due to being one version behind.
cabal is unable of updating, saying it wouldn't find the module System.Directory, exiting the install of Cabal-1.22.4.0 with ExitFailure 1 during the configure step.
gave up after about 3 hours.

(status on my desktop-machine, the one on my laptop is similar)

well, I'll try again another time.

I thought about installing Arch Linux as a base for some time now, and I guess I'll do it after learning Haskell a bit more.

**Comment by sternenseemann** [comment]
Rather install NixOS :)

**Comment by froozen** [comment]
Can this be closed, as it's something @blueburningcoder will have to sort out by themselves?

**Comment by fkarg** [comment]
Well, guess so. I'll figure a way out at some point (I hope).

**Comment by photm5** [comment]
> Rather install NixOS :)

[Nix](https://nixos.org/nix/) on itself should work too.

**Comment by sternenseemann** [comment]
Reopen this, if the issue still exists. Thank you
