### ISSUE TITLE
Ensure that packet size is set correctly

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/haskell-ricochet#25]
Should we introduce a check and a return type of `Maybe ByteString` in `dumpPacket` or do we just asume that we generate correct packets everywhere?

**Comment by sternenseemann** [comment]
Added the function `makePacket` which is always setting the correct packet size.

**Comment by photm5** [comment]
This wouldn’t happen with idris ;)... However, we could choose to only expose `makePacket`.
