### ISSUE TITLE
Implement Network.Ricochet.Crypto

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/haskell-ricochet#29]
We will need a module with nice crypto-related utility functions.
One thing we need is the generation of 1024-Bit private RSA keys in base64 for `network-anonymous-tor`.

**Comment by photm5** [comment]
Well, I’m not so sure anymore if there’s everything we need in HsOpenSSL, since it’s not a complete binding...

**Comment by photm5** [comment]
> One thing we need is the generation of 1024-Bit private RSA keys in base64 for network-anonymous-tor.

What does that mean?  DER-encoded and then base64?  We definitely need DER-encoding for the ricochet protocol anyways. I found [a PR that adds DER-encoding to HsOpenSSL](https://github.com/phonohawk/HsOpenSSL/pull/39), but it’s not been merged yet, so we might need to maintain our own fork...

**Comment by photm5** [comment]
Oh, the DER-encoding in that PR seems to be for certificates, so I’m not sure if that’s of use.

**Comment by froozen** [comment]
It doesn't seem to be maintained anymore. Kind of a bummer. Maintaining a fork would  suck really hard.

**Comment by sternenseemann** [comment]
I think this screws HsOpenSSL for the moment.

Since we are an experimental project why not use (experimental) saltine?

**Comment by photm5** [comment]
Because it doesn’t have everything we need, too.  We could, however see whether we have everything if we take RSA from saltine, and sha256 etc. from HsOpenSSL.

**Comment by sternenseemann** [comment]
We can depend on multiple libraries since we will have our own abstraction layer.

**Comment by photm5** [comment]
Oh, we won’t be able to take RSA from saltine, as its signing uses ECC. See #23.

**Comment by photm5** [comment]
I just made a [PR](https://github.com/phonohawk/HsOpenSSL/pull/46) that adds DER en/decoding to HsOpenSSL.  I don’t think the maintainer is going to merge it though.  What do you guys think about binding to openssl in our repo?  (That would essentially mean copying the RSA module from HsOpenSSL, in order to save us the work of maintaining a whole fork.)

**Comment by froozen** [comment]
It wouldn't be neat, but if that's the best way to go, we'll just have to do it.

**Comment by sternenseemann** [comment]
I don't like the idea of using OpenSSL at all actually.

**Comment by froozen** [comment]
What would you propose doing instead then?

**Comment by sternenseemann** [comment]
I don't know frankly.

**Comment by photm5** [comment]
Oh, we need DER encoding/decoding of _private_ keys for Tor...  I’ll need to add that...
