### ISSUE TITLE
Write nice monadic run functions

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/haskell-ricochet#33]
As we're exporting our own monad, we should provide some pleasant functions to "run" it.
I'd propose
`startRicochet :: Socket -> [Contact] -> PortID -> Map Word8 (Connectiont -> Ricochet ()) -> IO ()`
and
`startRicochet' ::  ByteString -> PortID -> [Contact] -> PortID -> Map Word8 (Connectiont -> Ricochet ()) -> IO ()`

The second one takes the private key and the Tor control port and does the port-mapping for the user.

**Comment by sternenseemann** [comment]
Proper definition:

``` haskell
startRicochet ::  Socket -> [Contact] -> PortID -> Versions -> IO ()
startRicochet' :: ByteString -> PortID -> [Contact] -> PortID -> Versions -> IO ()
```

**Comment by froozen** [comment]
This would also be the practical application of #12.
