### ISSUE TITLE
Add a usable environment for updating and using nix expressions

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/haskell-ricochet#35]
A improvement of `sahe`, maybe?

**Comment by froozen** [comment]
I don't really get what you mean. Could you elaborate this in more detail?

**Comment by sternenseemann** [comment]
In @shak-mar's new branch we got a reasonable number of nix expressions.

**Comment by froozen** [comment]
OK, that makes sense. What would you propose doing? Writitng a bash script to generate the nix-expressions with the help of cabal2nix?

**Comment by sternenseemann** [comment]
Indeed something like that.

**Comment by froozen** [comment]
@shak-mar Do you want to do it, as you already created the expressions in your branch?

**Comment by photm5** [comment]
I don’t get what you want me to do. Do you request a bash script to generate the nix expressions? Something like:

``` bash
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p cabal2nix
for p in hprotoc protocol-buffers protocol-buffers-descriptor; do
  cabal2nix cabal://$p > $p.nix
done
```

Note that you need to have run `cabal update` at least once beforehand.

**Comment by froozen** [comment]
Adding an appropriate note to `CONTRIBUTING.md` should be enough.

``` bash
cabal2nix $your_source_of_choice > $package_name.nix
```

And then adding the following line to the folded list in `shell.nix` is all there is to do.

``` nix
(entry ${packageName})
```
