### ISSUE TITLE
Rewrite README.adoc

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/haskell-ricochet#50]
`README.adoc` should be rewritten at some point — for good reasons.

**Comment by sternenseemann** [comment]
:heart:

**Comment by photm5** [comment]
We should review whether the “nice features” under [Idea](https://github.com/Jugendhackt/haskell-ricochet#idea) are actually true.  Eg, Tor doesn’t change keys during running sessions, so it’s not really Perfect Forward Secrecy, which is part of Off The Record.

**Comment by sternenseemann** [comment]
Anyone willing to commit for that?
