### ISSUE TITLE
Connection via Tor

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/haskell-ricochet#6]
We need send to connect to and via Tor.

**Comment by photm5** [comment]
This is just a matter of opening a tcp connection over a socks proxy.

**Comment by sternenseemann** [comment]
`network-anonymous-tor` is the best package to work with.

**Comment by photm5** [comment]
I’d recommend postponing all of the Tor control port stuff for some while.

**Comment by sternenseemann** [comment]
We use `socks` for connecting to TOR.
