### ISSUE TITLE
Add Datastructures according to the protobuf specs, and their Lenses

### ISSUE THREAD

**Issue by photm5** [Jugendhackt/haskell-ricochet#9]
We chose `protocol-buffers` and `hprotoc` in #1, now let’s put it to use!  We’ll also want to access them using lenses.

**Comment by froozen** [comment]
What about adding automatic lens-generation support to `hprotoc`? Is that part of this issue?

**Comment by photm5** [comment]
Guess who already created a pull request for this :smile:: https://github.com/k-bx/protocol-buffers/pull/12. Sadly, NixOS packages version 2.1.6, and the lenses feature is in 2.1.7, so we’ll have to find a solution on that end. But it is part of this issue, yes.

**Comment by sternenseemann** [comment]
Oh, I guess I know this guy :new_moon_with_face:

**Comment by photm5** [comment]
I pushed some nix expressions to `hprotobuf-lenses` for everyone to play around with.  One thing I noticed was that extension keys are prepended with an underscore too, even though they are not part of a record, and there is no lens generated for them.  (eg. `client_cookie` in `AuthHiddenService.hs` becomes `_client_cookie`.)

**Comment by photm5** [comment]
I pushed some lenses to `hprotobuf-lenses`, so there’s some fun to have:

``` haskell
ghci> :set -XOverloadedStrings
ghci> let p = "\NUL=\NUL\NUL\n7\b\SOH\DC2\USim.ricochet.auth.hidden-service\130\194\ETX\DLE\226Kx\238\190\234\215\&4\252\&9\233\231Vo\\\205" -- copied from #21
ghci> p ^? packet . pPacketData . msg . open_channel . ext client_cookie . _Just
Just "\226Kx\238\190\234\215\&4\252\&9\233\231Vo\\\205"
```
